apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-config"
  namespace: default
data:
  maxtext_dataset_bench.py: |-
{{ .Files.Get "maxtext_dataset_bench.py" | indent 4 }}
  standalone_dataloader.py: |-
{{ .Files.Get "standalone_dataloader.py" | indent 4 }}
  dataset_generator.py: |-
{{ .Files.Get "dataset_generator.py" | indent 4 }}
  parquet_to_arrayrecord.py: |-
{{ .Files.Get "parquet_to_arrayrecord.py" | indent 4 }}
  requirements.txt: |-
{{ .Files.Get "requirements.txt" | indent 4 }}
